CREATE DATABASE IF NOT EXISTS ATSS;
USE ATSS;

CREATE TABLE FLIGHTS (
    FID VARCHAR(10) PRIMARY KEY,
    FNAME VARCHAR(50),
    ORIGIN VARCHAR(50),
    DESTINATION VARCHAR(50),
    DEPARTTIME TIME,
    ARRIVALTIME TIME,
    PRIORITY INT,
    DATEOFFLIGHT DATE,
    RUNWAY CHAR(1)
);

CREATE TABLE CREW (
    ID VARCHAR(10),
    NAME VARCHAR(50),
    FlightID VARCHAR(10),
    LASTFLIGHTTIME TIME,
    DATEOFFLIGHT DATE,
    PRIMARY KEY (ID, DATEOFFLIGHT),
    FOREIGN KEY (FlightID) REFERENCES FLIGHTS(FID)
);
